# Generated by Django 4.1.3 on 2022-11-24 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readlater',
            old_name='user',
            new_name='user_name',
        ),
    ]
