# Generated by Django 4.1.3 on 2022-11-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='fav1',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='catagory',
            name='fav2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='catagory',
            name='fav3',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='catagory',
            name='fav4',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='catagory',
            name='fav5',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
