# Generated by Django 4.1.3 on 2022-11-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_catagory_fav1_alter_catagory_fav2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='fav1',
            field=models.CharField(default='Nothig', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='catagory',
            name='fav2',
            field=models.CharField(default='Nothig', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='catagory',
            name='fav3',
            field=models.CharField(default='Nothig', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='catagory',
            name='fav4',
            field=models.CharField(default='Nothig', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='catagory',
            name='fav5',
            field=models.CharField(default='Nothig', max_length=300, null=True),
        ),
    ]
